### PR TITLE
Feat db prefix

### PR DESCRIPTION
**Pull request by ThomasBS**
First of all: I really appreciate you putting this package out here in the open source world. So big thumbs up.

Now, I've might have gone a little overboard with this PR. Basicly I wanted to add the ability to use a prefix for database table names. Instead of having **replies** floating around in your database, you will now have the ability to prefix it from the configuration file with fx. "forum", so it will be named **forum_replies**.

I started adding the functionality and sort of cleaned up some of the code. There was some inconsistency in terms of indentation etc, so I ended up cleaning all of the code. Some changes might be because of my OCD. Sorry.

I thought I would create this PR so you could give me a response. Changes of this size would maybe be better just to create my own package, but since I'm still using 99% of your work, yeah ..

#### Changes made:
- Syntastic sugar (PSR-2 and stuff)
- Added a ``BaseModel`` to add the database table prefix to the ``$table`` property. The entities will extend upon the ``BaseModel`` instead of the ``Model`` from Eloquent.
- Edited files where the table name where hardcoded to instead read from config (forum.database.prefix)

### CODE REVIEW

**Comment by socieboy** [comment]
Thank you! Any help is appreciated, but you can send a pull request to my repository other way I don't agree to create your own package with the 99% of my code!

**Comment by socieboy** [comment]
Thank you for your time and help!
I know it could be a big change and a big contribution (nothing compare with the time I have done so far), but I don't considere to create your "own" package with the 99% of my code it's a good idea, you are entirely welcome to open the pull request and help us to make this package better.

**Comment by ThomasBS** [comment]
Alright, I will most likely do that. Expect a few PR's to be incoming! Cool with the merge :-)

**Comment by socieboy** [comment]
Thank you so much!
Make your pull request to the master branch!

**Pull request merged**
